name: Compile

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["master"]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          submodules: "true"
      - name: Setup and Build
        run: |
          # setup
          wget -q https://github.com/llvm/llvm-project/releases/download/llvmorg-19.1.7/LLVM-19.1.7-Linux-X64.tar.xz
          tar -xf LLVM-19.1.7-Linux-X64.tar.xz
          export PATH="$PATH:$PWD/LLVM-19.1.7-Linux-X64/bin"
          llvm-dis --version
          rustup toolchain add nightly-2023-03-03
          rustup component add rust-src --toolchain nightly-2023-03-03-x86_64-unknown-linux-gnu
          # build
          rustc ti83-fake-linker.rs -o ti83-fake-linker
          cargo ti83-build
  build-macos-arm:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          submodules: "true"
      - name: Setup and Build
        run: |
          # setup
          brew install llvm@15
          export PATH="/opt/homebrew/opt/llvm@15/bin:$PATH"
          llvm-dis --version
          rustup toolchain add nightly-2023-03-03
          rustup component add rust-src --toolchain nightly-2023-03-03-aarch64-apple-darwin
          # build
          rustc ti83-fake-linker.rs -o ti83-fake-linker
          cargo ti83-build
  build-macos-intel:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          submodules: "true"
      - name: Setup and Build
        run: |
          # setup
          brew install llvm@15
          export PATH="/usr/local/opt/llvm@15/bin:$PATH"
          llvm-dis --version
          rustup toolchain add nightly-2023-03-03
          rustup component add rust-src --toolchain nightly-2023-03-03-x86_64-apple-darwin
          # build
          rustc ti83-fake-linker.rs -o ti83-fake-linker
          cargo ti83-build
  