name: Linux Compile test

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          submodules: "true"
      - name: Build
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 16
          rustup toolchain add nightly-2023-03-03
          rustup component add rust-src --toolchain nightly-2023-03-03-x86_64-unknown-linux-gnu
          rustc ti83-fake-linker.rs -o ti83-fake-linker
          cargo ti83-build